export const keyToDisplayName = {
  firstName: "First Name",
  lastName: "Last Name",
  email: "E-mail",
  phone: "Phone",
  schoolName: "School Name",
  titleOfStudy: "Title of Study",
  startOfStudy: "Start of Study",
  endOfStudy: "End of Study",
  company: "Company",
  position: "Position",
  startOfEmployment: "Start of Employment",
  endOfEmployment: "End of Employment",
  ongoing: "Ongoing?",
  description: "Description",
};

export const keyToDisplayType = {
  firstName: "text",
  lastName: "text",
  email: "email",
  phone: "tel",
  schoolName: "text",
  titleOfStudy: "text",
  startOfStudy: "date",
  endOfStudy: "date",
  company: "text",
  position: "text",
  startOfEmployment: "date",
  endOfEmployment: "date",
  ongoing: "checkbox",
  description: "",
};
